spring:
  application:
    name: item-service
  cloud: 
    config: 
      overwide-none: true
  rabbitmq: 
    host: 192.168.64.140
    port: 15672
    usermane: admin
    password: admin
  
server:
  port: 8001
  
eureka:
  client: 
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
